// _ToolMobility_EOArchive.java
// Generated by EnterpriseObjects palette at Friday, October 29, 2004 4:48:34 PM US/Eastern

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _ToolMobility_EOArchive extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOForm _nsForm0;
    com.webobjects.eointerface.swing.EOFormCell _eoFormCell0;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOMatrix _nsMatrix0, _nsMatrix1, _nsMatrix2;
    com.webobjects.eointerface.swing.EOTextField _eoTextField0, _eoTextField1, _eoTextField2, _eoTextField3, _eoTextField4, _eoTextField5, _eoTextField6, _eoTextField7, _nsTextField0, _nsTextField1, _nsTextField2, _nsTextField3, _nsTextField4, _nsTextField5, _nsTextField6, _nsTextField7;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1, _nsBox2, _nsBox3, _nsBox4, _nsBox5;
    javax.swing.JButton _nsButton0, _nsButton1, _nsButton2;
    javax.swing.JComboBox _popup0;
    javax.swing.JPanel _nsView0;
    javax.swing.JRadioButton _jRadioButton0, _jRadioButton1, _jRadioButton2, _jRadioButton3, _jRadioButton4, _jRadioButton5, _jRadioButton6, _jRadioButton7, _jRadioButton8, _jRadioButton9;

    public _ToolMobility_EOArchive(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsBox5 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox4 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsBox3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _jRadioButton9 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Private"), "");
        _jRadioButton8 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Public"), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "resourceSourceID")) != null)) {
            _nsMatrix2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix2");
        } else {
            _nsMatrix2 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(2, 1, 0, 3), "");
        }

        _jRadioButton7 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Ch 8"), "");
        _jRadioButton6 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Ch 7"), "");
        _jRadioButton5 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Ch 6"), "Ch 4");
        _jRadioButton4 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Ch 5"), "Ch 3");
        _jRadioButton3 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Ch 4"), "");
        _jRadioButton2 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Ch 3"), "");
        _jRadioButton1 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Ch 2"), "Ch 2");
        _jRadioButton0 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Ch 1"), "Ch 1");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "shiftSelector")) != null)) {
            _nsMatrix1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix1");
        } else {
            _nsMatrix1 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(2, 4, 0, 3), "Matrix");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "shiftButton")) != null)) {
            _nsButton2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton2");
        } else {
            _nsButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton("Shift Selected Channel"), "Button");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "removeButton")) != null)) {
            _nsButton1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton1");
        } else {
            _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Remove"), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "newButton")) != null)) {
            _nsButton0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton0");
        } else {
            _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("New"), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "resourceMenuButton")) != null)) {
            _popup0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup0");
        } else {
            _popup0 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "");
        }

        _eoTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "mobilityMatrix")) != null)) {
            _nsMatrix0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix0");
        } else {
            _nsMatrix0 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(2, 4, 14, 2), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "resourceLabelID")) != null)) {
            _eoFormCell0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFormCell)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFormCell0");
        } else {
            _eoFormCell0 = (com.webobjects.eointerface.swing.EOFormCell)_registered(new com.webobjects.eointerface.swing.EOFormCell(), "");
        }

        _nsForm0 = (com.webobjects.eointerface.swing.EOForm)_registered(new com.webobjects.eointerface.swing.EOForm(1, 1, 1, 3), "");
        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "inspectorView")) != null)) {
            _nsBox0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsBox0");
        } else {
            _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        }

        _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Panel");
        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_nsMatrix2") == null) {
            _connect(_owner(), _nsMatrix2, "resourceSourceID");
        }

        if (_replacedObjects.objectForKey("_nsMatrix1") == null) {
            _connect(_owner(), _nsMatrix1, "shiftSelector");
        }

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _connect(_owner(), _nsButton2, "shiftButton");
        }

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _connect(_owner(), _nsButton1, "removeButton");
        }

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _connect(_owner(), _nsButton0, "newButton");
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _popup0.setModel(new javax.swing.DefaultComboBoxModel());
            _popup0.addItem("Default Mobility");
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _connect(_owner(), _popup0, "resourceMenuButton");
        }

        _eoTextField0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "registerValue", _eoTextField0), ""));
        _eoTextField1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "registerValue", _eoTextField1), ""));
        _eoTextField2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "registerValue", _eoTextField2), ""));
        _eoTextField3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "registerValue", _eoTextField3), ""));
        _eoTextField4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "registerValue", _eoTextField4), ""));
        _eoTextField5.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "registerValue", _eoTextField5), ""));
        _eoTextField6.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "registerValue", _eoTextField6), ""));
        _eoTextField7.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "registerValue", _eoTextField7), ""));

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _connect(_owner(), _nsMatrix0, "mobilityMatrix");
        }

        if (_replacedObjects.objectForKey("_nsBox0") == null) {
            _connect(_owner(), _nsBox0, "inspectorView");
        }

        if (_replacedObjects.objectForKey("_eoFormCell0") == null) {
            _connect(_owner(), _eoFormCell0, "resourceLabelID");
        }
    }

    protected void _init() {
        super._init();
        if (!(_nsBox5.getLayout() instanceof EOViewLayout)) { _nsBox5.setLayout(new EOViewLayout()); }
        _nsButton2.setSize(137, 24);
        _nsButton2.setLocation(37, 2);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox5.add(_nsButton2);
        _nsMatrix1.setSize(196, 39);
        _nsMatrix1.setLocation(5, 28);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsMatrix1, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox5.add(_nsMatrix1);
        if (!(_nsBox4.getLayout() instanceof EOViewLayout)) { _nsBox4.setLayout(new EOViewLayout()); }
        _nsBox5.setSize(211, 73);
        _nsBox5.setLocation(2, 16);
        ((EOViewLayout)_nsBox4.getLayout()).setAutosizingMask(_nsBox5, EOViewLayout.MinYMargin);
        _nsBox4.add(_nsBox5);
        _nsBox4.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Interactive Mobility Shifting", true, "Helvetica", 12, Font.PLAIN));
        _setFontForComponent(_nsTextField7, "Helvetica", 9, Font.PLAIN);
        _nsTextField7.setEditable(false);
        _nsTextField7.setOpaque(false);
        _nsTextField7.setText("4:");
        _nsTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField7.setSelectable(false);
        _nsTextField7.setEnabled(true);
        _nsTextField7.setBorder(null);
        _setFontForComponent(_nsTextField6, "Helvetica", 9, Font.PLAIN);
        _nsTextField6.setEditable(false);
        _nsTextField6.setOpaque(false);
        _nsTextField6.setText("8:");
        _nsTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField6.setSelectable(false);
        _nsTextField6.setEnabled(true);
        _nsTextField6.setBorder(null);
        _setFontForComponent(_nsTextField5, "Helvetica", 9, Font.PLAIN);
        _nsTextField5.setEditable(false);
        _nsTextField5.setOpaque(false);
        _nsTextField5.setText("7:");
        _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField5.setSelectable(false);
        _nsTextField5.setEnabled(true);
        _nsTextField5.setBorder(null);
        _setFontForComponent(_nsTextField4, "Helvetica", 9, Font.PLAIN);
        _nsTextField4.setEditable(false);
        _nsTextField4.setOpaque(false);
        _nsTextField4.setText("3:");
        _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField4.setSelectable(false);
        _nsTextField4.setEnabled(true);
        _nsTextField4.setBorder(null);
        _setFontForComponent(_nsTextField3, "Helvetica", 9, Font.PLAIN);
        _nsTextField3.setEditable(false);
        _nsTextField3.setOpaque(false);
        _nsTextField3.setText("2:");
        _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField3.setSelectable(false);
        _nsTextField3.setEnabled(true);
        _nsTextField3.setBorder(null);
        _setFontForComponent(_nsTextField2, "Helvetica", 9, Font.PLAIN);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(false);
        _nsTextField2.setText("6:");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);
        _nsTextField2.setBorder(null);
        _setFontForComponent(_nsTextField1, "Helvetica", 9, Font.PLAIN);
        _nsTextField1.setEditable(false);
        _nsTextField1.setOpaque(false);
        _nsTextField1.setText("5:");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField1.setSelectable(false);
        _nsTextField1.setEnabled(true);
        _nsTextField1.setBorder(null);
        _setFontForComponent(_nsTextField0, "Helvetica", 9, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("1:");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        if (!(_nsBox3.getLayout() instanceof EOViewLayout)) { _nsBox3.setLayout(new EOViewLayout()); }
        _nsMatrix0.setSize(187, 38);
        _nsMatrix0.setLocation(14, 0);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsMatrix0, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsMatrix0);
        _nsTextField0.setSize(17, 12);
        _nsTextField0.setLocation(-1, 3);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField0);
        _nsTextField1.setSize(17, 12);
        _nsTextField1.setLocation(-1, 22);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField1);
        _nsTextField2.setSize(17, 12);
        _nsTextField2.setLocation(49, 22);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField2);
        _nsTextField3.setSize(17, 12);
        _nsTextField3.setLocation(49, 3);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField3);
        _nsTextField4.setSize(17, 12);
        _nsTextField4.setLocation(99, 3);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField4);
        _nsTextField5.setSize(17, 12);
        _nsTextField5.setLocation(99, 22);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField5);
        _nsTextField6.setSize(17, 12);
        _nsTextField6.setLocation(149, 22);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField6, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField6);
        _nsTextField7.setSize(17, 12);
        _nsTextField7.setLocation(149, 3);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField7, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField7);
        if (!(_nsBox2.getLayout() instanceof EOViewLayout)) { _nsBox2.setLayout(new EOViewLayout()); }
        _nsBox3.setSize(209, 42);
        _nsBox3.setLocation(2, 16);
        ((EOViewLayout)_nsBox2.getLayout()).setAutosizingMask(_nsBox3, EOViewLayout.MinYMargin);
        _nsBox2.add(_nsBox3);
        _nsBox2.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Mobility Shifts by Channel", true, "Helvetica", 12, Font.PLAIN));
        _setFontForComponent(_jRadioButton9, "Helvetica", 12, Font.PLAIN);
        _setFontForComponent(_jRadioButton8, "Helvetica", 12, Font.PLAIN);

        if (_replacedObjects.objectForKey("_nsMatrix2") == null) {
            _jRadioButton8.setSize(61, 19);
            _jRadioButton8.setLocation(0, 0);
            _nsMatrix2.add(_jRadioButton8);
            _jRadioButton9.setSize(61, 19);
            _jRadioButton9.setLocation(0, 22);
            _nsMatrix2.add(_jRadioButton9);
        }

        _setFontForComponent(_jRadioButton7, "Helvetica", 12, Font.PLAIN);
        _setFontForComponent(_jRadioButton6, "Helvetica", 12, Font.PLAIN);
        _setFontForComponent(_jRadioButton5, "Helvetica", 12, Font.PLAIN);
        _setFontForComponent(_jRadioButton4, "Helvetica", 12, Font.PLAIN);
        _setFontForComponent(_jRadioButton3, "Helvetica", 12, Font.PLAIN);
        _setFontForComponent(_jRadioButton2, "Helvetica", 12, Font.PLAIN);
        _setFontForComponent(_jRadioButton1, "Helvetica", 12, Font.PLAIN);
        _setFontForComponent(_jRadioButton0, "Helvetica", 12, Font.PLAIN);

        if (_replacedObjects.objectForKey("_nsMatrix1") == null) {
            _jRadioButton0.setSize(49, 18);
            _jRadioButton0.setLocation(0, 0);
            _nsMatrix1.add(_jRadioButton0);
            _jRadioButton1.setSize(49, 18);
            _jRadioButton1.setLocation(49, 0);
            _nsMatrix1.add(_jRadioButton1);
            _jRadioButton2.setSize(49, 18);
            _jRadioButton2.setLocation(98, 0);
            _nsMatrix1.add(_jRadioButton2);
            _jRadioButton3.setSize(49, 18);
            _jRadioButton3.setLocation(147, 0);
            _nsMatrix1.add(_jRadioButton3);
            _jRadioButton4.setSize(49, 18);
            _jRadioButton4.setLocation(0, 21);
            _nsMatrix1.add(_jRadioButton4);
            _jRadioButton5.setSize(49, 18);
            _jRadioButton5.setLocation(49, 21);
            _nsMatrix1.add(_jRadioButton5);
            _jRadioButton6.setSize(49, 18);
            _jRadioButton6.setLocation(98, 21);
            _nsMatrix1.add(_jRadioButton6);
            _jRadioButton7.setSize(49, 18);
            _jRadioButton7.setLocation(147, 21);
            _nsMatrix1.add(_jRadioButton7);
        }

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _setFontForComponent(_nsButton2, "Helvetica", 12, Font.PLAIN);
            _nsButton2.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _setFontForComponent(_nsButton1, "Helvetica", 12, Font.PLAIN);
            _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _setFontForComponent(_nsButton0, "Helvetica", 12, Font.PLAIN);
            _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _setFontForComponent(_popup0, "Helvetica", 12, Font.PLAIN);
        }

        _setFontForComponent(_eoTextField7, "Helvetica", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField6, "Helvetica", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField5, "Helvetica", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField4, "Helvetica", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField3, "Helvetica", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField2, "Helvetica", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField1, "Helvetica", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField0, "Helvetica", 9, Font.PLAIN);

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _eoTextField0.setSize(36, 18);
            _eoTextField0.setLocation(0, 0);
            _nsMatrix0.add(_eoTextField0);
            _eoTextField1.setSize(36, 18);
            _eoTextField1.setLocation(50, 0);
            _nsMatrix0.add(_eoTextField1);
            _eoTextField2.setSize(36, 18);
            _eoTextField2.setLocation(100, 0);
            _nsMatrix0.add(_eoTextField2);
            _eoTextField3.setSize(36, 18);
            _eoTextField3.setLocation(150, 0);
            _nsMatrix0.add(_eoTextField3);
            _eoTextField4.setSize(36, 18);
            _eoTextField4.setLocation(0, 20);
            _nsMatrix0.add(_eoTextField4);
            _eoTextField5.setSize(36, 18);
            _eoTextField5.setLocation(50, 20);
            _nsMatrix0.add(_eoTextField5);
            _eoTextField6.setSize(36, 18);
            _eoTextField6.setLocation(100, 20);
            _nsMatrix0.add(_eoTextField6);
            _eoTextField7.setSize(36, 18);
            _eoTextField7.setLocation(150, 20);
            _nsMatrix0.add(_eoTextField7);
        }

        if (_replacedObjects.objectForKey("_eoFormCell0") == null) {
            _setFontForComponent(_eoFormCell0, "Helvetica", 12, Font.PLAIN);
            _eoFormCell0.setTitle("Mobility Label:");
            _eoFormCell0.setTitleWidth(88);
            _eoFormCell0.fieldComponent().setPreferredSize(new Dimension(2, 20));
            _eoFormCell0.titleComponent().setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        }

        _eoFormCell0.setSize(0, 0);
        _eoFormCell0.setLocation(-1, 0);
        _nsForm0.add(_eoFormCell0);
        _setFontForComponent(_nsForm0, "Helvetica", 12, Font.PLAIN);
        if (!(_nsBox1.getLayout() instanceof EOViewLayout)) { _nsBox1.setLayout(new EOViewLayout()); }
        _nsForm0.setSize(211, 21);
        _nsForm0.setLocation(21, 20);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsForm0, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsBox1.add(_nsForm0);
        _nsButton1.setSize(72, 24);
        _nsButton1.setLocation(96, 78);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinXMargin | EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsBox1.add(_nsButton1);
        _popup0.setSize(142, 26);
        _popup0.setLocation(23, 49);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_popup0, EOViewLayout.MinXMargin | EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsBox1.add(_popup0);
        _nsButton0.setSize(51, 24);
        _nsButton0.setLocation(20, 78);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinXMargin | EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsBox1.add(_nsButton0);
        _nsBox2.setSize(213, 60);
        _nsBox2.setLocation(16, 204);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsBox2, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsBox2);
        _nsBox4.setSize(215, 91);
        _nsBox4.setLocation(19, 110);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsBox4, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsBox4);
        _nsMatrix2.setSize(61, 41);
        _nsMatrix2.setLocation(172, 49);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsMatrix2, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsMatrix2);

        if (_replacedObjects.objectForKey("_nsBox0") == null) {
            if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
            _nsBox1.setSize(246, 280);
            _nsBox1.setLocation(2, 16);
            ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
            _nsBox0.add(_nsBox1);
            _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Constant Mobility Shift", true, "Helvetica", 12, Font.PLAIN));
        }

        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsBox0.setSize(250, 298);
        _nsBox0.setLocation(41, 15);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox0);
        _nsView0.setSize(329, 396);
        _eoFrame0.setTitle("Panel");
        _eoFrame0.setLocation(271, 551);
        _eoFrame0.setSize(329, 396);
    }
}
