// _Preferences_EOArchive.java
// Generated by EnterpriseObjects palette at Thursday, October 28, 2004 5:09:57 PM US/Eastern

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.eointerface.swing.EOTable._EOTableColumn;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _Preferences_EOArchive extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOFrame _eoFrame0, _eoFrame1;
    com.webobjects.eointerface.swing.EOMatrix _nsMatrix0, _nsMatrix1;
    com.webobjects.eointerface.swing.EOTable _nsTableView0;
    com.webobjects.eointerface.swing.EOTable._EOTableColumn _eoTableColumn0;
    com.webobjects.eointerface.swing.EOTextArea _nsTextView0;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1, _nsView0, _nsView1, _nsView2;
    javax.swing.JButton _nsButton0, _nsButton1, _nsButton2, _nsButton3, _nsButton4;
    javax.swing.JCheckBox _jCheckBox0, _jCheckBox1, _nsButton5, _nsButton6;
    javax.swing.JPanel _nsView3, _nsView4;
    javax.swing.JRadioButton _jRadioButton0, _jRadioButton1, _jRadioButton2;
    javax.swing.JTabbedPane _nsTabView0;

    public _Preferences_EOArchive(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsView2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        _nsView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox");
        _nsView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsTabView0 = (javax.swing.JTabbedPane)_registered(new javax.swing.JTabbedPane(), "NSTabView");
        _nsButton4 = (javax.swing.JButton)_registered(new javax.swing.JButton("Add"), "NSButton");
        _nsButton3 = (javax.swing.JButton)_registered(new javax.swing.JButton("Delete"), "NSButton1");
        _nsButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton("Set"), "");
        _jCheckBox1 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Load private tools"), "NSButtonCell");
        _jCheckBox0 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Load public tools"), "NSButtonCell1");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "toolLoadID")) != null)) {
            _nsMatrix1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix1");
        } else {
            _nsMatrix1 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(2, 1, 4, 4), "NSMatrix");
        }

        _eoTableColumn0 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bundleDirs")) != null)) {
            _nsTableView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTable)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTableView0");
        } else {
            _nsTableView0 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "debugModeID")) != null)) {
            _nsButton6 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton6");
        } else {
            _nsButton6 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Debug Logging to Console"), "NSButton");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "threadingID")) != null)) {
            _nsButton5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton5");
        } else {
            _nsButton5 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Use Background Processing Threads"), "NSButton1");
        }

        _jRadioButton2 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Expert"), "NSButtonCell");
        _jRadioButton1 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Novice"), "NSButtonCell1");
        _jRadioButton0 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Beginner"), "NSButtonCell2");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "expertModeID")) != null)) {
            _nsMatrix0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix0");
        } else {
            _nsMatrix0 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(3, 1, 0, 3), "NSMatrix");
        }

        _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Revert"), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "prefPanel")) != null)) {
            _eoFrame1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame1");
        } else {
            _eoFrame1 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "PrefPanel");
        }

        _nsView4 = (JPanel)_eoFrame1.getContentPane();
        _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("help"), "NSButton");
        _nsTextView0 = (com.webobjects.eointerface.swing.EOTextArea)_registered(new com.webobjects.eointerface.swing.EOTextArea(), "");
        _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "HelpPanel");
        _nsView3 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        _nsButton4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "addResourcePath", _nsButton4), ""));
        _nsButton3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "deleteResourcePath", _nsButton3), ""));

        if (_replacedObjects.objectForKey("_eoFrame1") == null) {
            _connect(_eoFrame1, _owner(), "delegate");
        }

        _nsButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "setParams", _nsButton2), ""));

        if (_replacedObjects.objectForKey("_nsMatrix1") == null) {
            _connect(_owner(), _nsMatrix1, "toolLoadID");
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_nsTableView0, _owner(), "dataSource");
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_owner(), _nsTableView0, "bundleDirs");
        }

        _nsButton6.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changeDebugMode", _nsButton6), ""));

        if (_replacedObjects.objectForKey("_nsButton6") == null) {
            _connect(_owner(), _nsButton6, "debugModeID");
        }

        if (_replacedObjects.objectForKey("_nsButton5") == null) {
            _connect(_owner(), _nsButton5, "threadingID");
        }

        _jRadioButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "switchExpertMode", _jRadioButton0), ""));
        _jRadioButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "switchExpertMode", _jRadioButton1), ""));
        _jRadioButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "switchExpertMode", _jRadioButton2), ""));

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _connect(_owner(), _nsMatrix0, "expertModeID");
        }

        if (_replacedObjects.objectForKey("_eoFrame1") == null) {
            _connect(_owner(), _eoFrame1, "prefPanel");
        }

        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "resetPanel", _nsButton1), ""));
    }

    protected void _init() {
        super._init();
        if (!(_nsView2.getLayout() instanceof EOViewLayout)) { _nsView2.setLayout(new EOViewLayout()); }
        _nsButton6.setSize(178, 18);
        _nsButton6.setLocation(55, 67);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton6, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton6);
        _nsButton5.setSize(233, 18);
        _nsButton5.setLocation(55, 90);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton5, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton5);
        _setFontForComponent(_nsTextField0, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("Resource Paths");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField0.setSelectable(true);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        if (!(_nsView1.getLayout() instanceof EOViewLayout)) { _nsView1.setLayout(new EOViewLayout()); }
        _nsTableView0.setSize(301, 78);
        _nsTableView0.setLocation(15, 82);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTableView0, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTableView0);
        _nsButton4.setSize(77, 33);
        _nsButton4.setLocation(181, 166);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton4, EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton4);
        _nsButton3.setSize(77, 33);
        _nsButton3.setLocation(58, 165);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton3, EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton3);
        _nsTextField0.setSize(193, 17);
        _nsTextField0.setLocation(65, 53);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField0);
        _nsMatrix1.setSize(127, 40);
        _nsMatrix1.setLocation(101, 7);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsMatrix1, EOViewLayout.MinYMargin);
        _nsView1.add(_nsMatrix1);
        if (!(_nsBox1.getLayout() instanceof EOViewLayout)) { _nsBox1.setLayout(new EOViewLayout()); }
        _nsMatrix0.setSize(93, 61);
        _nsMatrix0.setLocation(18, 13);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsMatrix0, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsMatrix0);
        _nsButton0.setSize(49, 33);
        _nsButton0.setLocation(116, 29);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsButton0);
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(179, 79);
        _nsBox1.setLocation(2, 17);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Level Of Expertise", true, "Lucida Grande", 12, Font.PLAIN));
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsBox0.setSize(183, 98);
        _nsBox0.setLocation(69, 42);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox0);
        _nsTabView0.addTab("Expertise", _nsView0);
        _nsTabView0.addTab("Resources", _nsView1);
        _nsTabView0.addTab("Misc.", _nsView2);
        _nsTabView0.setSelectedIndex(2);
        _setFontForComponent(_nsButton4, "Lucida Grande", 13, Font.PLAIN);
        _nsButton4.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton3, "Lucida Grande", 13, Font.PLAIN);
        _nsButton3.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton2, "Helvetica", 12, Font.PLAIN);
        _nsButton2.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jCheckBox1, "Lucida Grande", 12, Font.PLAIN);
        _setFontForComponent(_jCheckBox0, "Lucida Grande", 12, Font.PLAIN);

        if (_replacedObjects.objectForKey("_nsMatrix1") == null) {
            _jCheckBox0.setSize(127, 18);
            _jCheckBox0.setLocation(0, 0);
            _nsMatrix1.add(_jCheckBox0);
            _jCheckBox1.setSize(127, 18);
            _jCheckBox1.setLocation(0, 22);
            _nsMatrix1.add(_jCheckBox1);
        }

        _eoTableColumn0.setMinWidth(40);
        _eoTableColumn0.setMaxWidth(1000);
        _eoTableColumn0.setPreferredWidth(281);
        _eoTableColumn0.setWidth(281);
        _eoTableColumn0.setResizable(true);
        _eoTableColumn0.setHeaderValue("Resource Paths");
        if ((_eoTableColumn0.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn0.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _nsTableView0.table().addColumn(_eoTableColumn0);
            _setFontForComponent(_nsTableView0.table().getTableHeader(), "Lucida Grande", 12, Font.PLAIN);
            _nsTableView0.table().setRowHeight(19);
        }

        if (_replacedObjects.objectForKey("_nsButton6") == null) {
            _setFontForComponent(_nsButton6, "Lucida Grande", 12, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton5") == null) {
            _setFontForComponent(_nsButton5, "Lucida Grande", 12, Font.PLAIN);
        }

        _setFontForComponent(_jRadioButton2, "Helvetica", 12, Font.PLAIN);
        _setFontForComponent(_jRadioButton1, "Helvetica", 12, Font.PLAIN);
        _setFontForComponent(_jRadioButton0, "Helvetica", 12, Font.PLAIN);

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _jRadioButton0.setSize(93, 18);
            _jRadioButton0.setLocation(0, 0);
            _nsMatrix0.add(_jRadioButton0);
            _jRadioButton1.setSize(93, 18);
            _jRadioButton1.setLocation(0, 21);
            _nsMatrix0.add(_jRadioButton1);
            _jRadioButton2.setSize(93, 18);
            _jRadioButton2.setLocation(0, 42);
            _nsMatrix0.add(_jRadioButton2);
        }

        _setFontForComponent(_nsButton1, "Helvetica", 12, Font.PLAIN);
        _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        if (!(_nsView4.getLayout() instanceof EOViewLayout)) { _nsView4.setLayout(new EOViewLayout()); }
        _nsButton1.setSize(93, 33);
        _nsButton1.setLocation(43, 232);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinYMargin);
        _nsView4.add(_nsButton1);
        _nsButton2.setSize(93, 33);
        _nsButton2.setLocation(167, 233);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinYMargin);
        _nsView4.add(_nsButton2);
        _nsTabView0.setSize(338, 241);
        _nsTabView0.setLocation(-11, -5);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsTabView0, EOViewLayout.MinYMargin);
        _nsView4.add(_nsTabView0);

        if (_replacedObjects.objectForKey("_eoFrame1") == null) {
            _nsView4.setSize(316, 258);
            _eoFrame1.setTitle("Preferences");
            _eoFrame1.setLocation(107, 407);
            _eoFrame1.setSize(316, 258);
        }

        _setFontForComponent(_nsButton0, "Helvetica", 12, Font.PLAIN);
        _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_eoFrame0, "makeKeyAndOrderFront", _nsButton0), ""));
        _nsTextView0.setEditable(false);
        _nsTextView0.setOpaque(true);
        _nsTextView0.setText("Beginner level: In this mode the user is only allowed to:\n1) load scripts\n2) step through scripts seeing effect of each tool and tool's parameters\n3) apply script to multiple lanes\n\nNovice level: In this mode the user is allowed to do all actions of the beginner level plus the following additional actions:\n1) edit and save scripts\n2) users has a private set of scripts and tool resources\n3) can set separate execution and editing points\n\nExpert level: In this mode the user is allowed to do all actions of the novice level with the following exceptions:\n1) single clicking on a script entry only sets the position in the script.  It does not show the parameters of the current tool in the script.\n2) double clicking on a script entry will show that tools parameters in the ToolPanel.\n");
        _setFontForComponent(_nsTextView0.textArea(), "Helvetica", 12, Font.PLAIN + Font.BOLD);
        if (!(_nsView3.getLayout() instanceof EOViewLayout)) { _nsView3.setLayout(new EOViewLayout()); }
        _nsTextView0.setSize(555, 276);
        _nsTextView0.setLocation(8, 3);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsTextView0, EOViewLayout.MinYMargin);
        _nsView3.add(_nsTextView0);
        _nsView3.setSize(572, 288);
        _eoFrame0.setTitle("Explanation of Levels of Expertise");
        _eoFrame0.setLocation(482, 78);
        _eoFrame0.setSize(572, 288);
    }
}
