// _StatusController_EOArchive.java
// Generated by EnterpriseObjects palette at Friday, October 29, 2004 4:43:03 PM US/Eastern

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _StatusController_EOArchive extends com.webobjects.eoapplication.EOArchive {
    BoxView _nsCustomView0;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0, _eoFrame1;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField2, _nsTextField3, _nsTextField4;
    javax.swing.JPanel _nsView0, _nsView1;

    public _StatusController_EOArchive(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _eoFrame1 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "AltViews");
        _nsView1 = (JPanel)_eoFrame1.getContentPane();

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "messageText")) != null)) {
            _nsTextField4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField4");
        } else {
            _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "Field31");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "statusBoxView")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (BoxView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (BoxView)_registered(new BoxView(), "CustomView");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "processNameText")) != null)) {
            _nsTextField3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField3");
        } else {
            _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "altStatus")) != null)) {
            _nsTextField2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField2");
        } else {
            _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "Field");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "masterMessage")) != null)) {
            _nsTextField1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField1");
        } else {
            _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        }

        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "Field2");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "statusPanel")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "StatusWindow");
        }

        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _connect(_owner(), _nsTextField4, "messageText");
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "statusBoxView");
        }

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "statusPanel");
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _connect(_owner(), _nsTextField3, "processNameText");
        }

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _connect(_owner(), _nsTextField2, "altStatus");
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _connect(_owner(), _nsTextField1, "masterMessage");
        }
    }

    protected void _init() {
        super._init();
        if (!(_nsView1.getLayout() instanceof EOViewLayout)) { _nsView1.setLayout(new EOViewLayout()); }
        _nsTextField4.setSize(477, 15);
        _nsTextField4.setLocation(93, 78);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField4);
        _nsView1.setSize(567, 101);
        _eoFrame1.setTitle("Off Screen Window with Alt Views");
        _eoFrame1.setLocation(358, 176);
        _eoFrame1.setSize(567, 101);

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _setFontForComponent(_nsTextField4, "Helvetica", 12, Font.PLAIN + Font.ITALIC);
            _nsTextField4.setEditable(false);
            _nsTextField4.setOpaque(false);
            _nsTextField4.setText("Message Text");
            _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField4.setSelectable(false);
            _nsTextField4.setEnabled(true);
            _nsTextField4.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _setFontForComponent(_nsTextField3, "Helvetica", 12, Font.PLAIN + Font.ITALIC);
            _nsTextField3.setEditable(false);
            _nsTextField3.setOpaque(false);
            _nsTextField3.setText("No Active Processing");
            _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField3.setSelectable(false);
            _nsTextField3.setEnabled(true);
            _nsTextField3.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _setFontForComponent(_nsTextField2, "Times", 14, Font.PLAIN + Font.BOLD);
            _nsTextField2.setEditable(false);
            _nsTextField2.setOpaque(false);
            _nsTextField2.setText("% Complete:");
            _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            _nsTextField2.setSelectable(false);
            _nsTextField2.setEnabled(true);
            _nsTextField2.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _setFontForComponent(_nsTextField1, "Helvetica", 12, Font.PLAIN + Font.BOLD);
            _nsTextField1.setEditable(false);
            _nsTextField1.setOpaque(false);
            _nsTextField1.setText("Title");
            _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            _nsTextField1.setSelectable(false);
            _nsTextField1.setEnabled(true);
            _nsTextField1.setBorder(null);
        }

        _setFontForComponent(_nsTextField0, "Times", 14, Font.PLAIN + Font.BOLD);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("Process:");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsTextField0.setSize(92, 18);
        _nsTextField0.setLocation(1, 20);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField0);
        _nsTextField1.setSize(300, 15);
        _nsTextField1.setLocation(8, 3);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField1);
        _nsTextField3.setSize(221, 15);
        _nsTextField3.setLocation(97, 22);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField3);
        _nsTextField2.setSize(92, 18);
        _nsTextField2.setLocation(1, 44);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField2);
        _nsCustomView0.setSize(208, 20);
        _nsCustomView0.setLocation(92, 43);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsCustomView0, EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsView0.add(_nsCustomView0);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView0.setSize(314, 68);
            _eoFrame0.setTitle("Process Status");
            _eoFrame0.setLocation(496, 192);
            _eoFrame0.setSize(314, 68);
        }
    }
}
